language: objective-c
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisExample_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/TravisExample_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild -workspace DemoTravisPods.xcworkspace -scheme DemoTravisPods -sdk iphoneos  -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xcodebuild test -workspace DemoTravisPods.xcworkspace  -scheme DemoTravisPods  -sdk  iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="DemoTravisPods"
  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - secure: AxYEIeCAoBR9+ZlVbBnpUK2rKwhDa3NfWfGF7PlURLwgyLfL4X8itIqCr3rqDvMmg1z19eNLevavNN2UG1WOA9JmA8FWg2fwCIMPEh9NEvBHveSDrX5I0Qpf/WXtD2TFmfaxWmssxuWVQnxVr6U20eppP0yybFLNfMjblrkOPAQ=
  - secure: lj/EZX+k/ebt2PaV650EVf/R7Wi/aaiJVI/Z08H2cEHT3pzQEIV4Kxm5Ygrt779ErgI9XCpwTSURFULm5+Yex5fGd6Bk5G34K+CemoClE4OvkWx0I9RzFEHgtR8xp8vL11UGdF2UA+iEmttRaj/NpSJ2F+HGOzZJEBoj4HJfTmc=
  - secure: Qic0Wz8zD9GIFWJ+VnWZA2B43JaE3gXtKB8sU3C7UGP9icuD/UEWBogzA5OHqv2nDZ6u2U+yA/GK2sPKhjsQeOkiEQ0xCnnPIUsmDk80VpMpP246HI1Jj1ovLNV632AfDEwb/Y77h77ubHtPgQLvD0V/WvGJC8lZCcSouUeIAuA=
  - secure: DjfWe86aT1jT7F7x0Ie+Za/VDnSlTUZpyd4kgdSXm1qj/JLq59/FLuyWouSkh22EnOSK5iq+LUKPxQczZjSR9ntRRHbaMd8MfVQ6dIVb8+xpAOGXL26nac+XSVCIBu8XDQL9YDI3tw/9cIKyGf8aYzLD5uXnVt1boPHGprtpCT8=
